// <auto-generated />
using System;
using ElTriangulitoP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElTriangulitoP.Migrations
{
    [DbContext(typeof(ElTriangulitoDBContext))]
    [Migration("20250310200312_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElTriangulitoP.Models.Mesas", b =>
                {
                    b.Property<int>("id_mesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_mesa"));

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_mesa");

                    b.ToTable("mesas");
                });

            modelBuilder.Entity("ElTriangulitoP.Models.Ordenes", b =>
                {
                    b.Property<int>("id_orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_orden"));

                    b.Property<string>("comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_combo")
                        .HasColumnType("int");

                    b.Property<int>("id_mesa")
                        .HasColumnType("int");

                    b.Property<int?>("id_plato")
                        .HasColumnType("int");

                    b.Property<int?>("id_promocion")
                        .HasColumnType("int");

                    b.Property<string>("nombre_cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_orden");

                    b.ToTable("ordenes");
                });

            modelBuilder.Entity("ElTriangulitoP.Models.Platos", b =>
                {
                    b.Property<int>("id_plato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_plato"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_plato");

                    b.ToTable("platos");
                });

            modelBuilder.Entity("ElTriangulitoP.Models.Promociones", b =>
                {
                    b.Property<int>("id_promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_promocion"));

                    b.Property<DateTime?>("fecha_fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_inicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_combo")
                        .HasColumnType("int");

                    b.Property<int?>("id_plato")
                        .HasColumnType("int");

                    b.Property<decimal?>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_promocion");

                    b.ToTable("promociones");
                });

            modelBuilder.Entity("ElTriangulitoP.Models.combos", b =>
                {
                    b.Property<int>("id_combo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_combo"));

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id_combo");

                    b.ToTable("combos");
                });
#pragma warning restore 612, 618
        }
    }
}
